version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: acx
      POSTGRES_PASSWORD: acx
      POSTGRES_DB: acx
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: .
    environment:
      DATABASE_URL: postgresql+asyncpg://acx:acx@db:5432/acx
      ADCTX_API_KEYS: secret123
    ports:
      - "8000:8000"
    depends_on:
      - db

  agent:
    build: .
    command: python cursor_client_example/main.py
    environment:
      MEMORY_API: http://api:8000
      MEMORY_API_KEY: secret123
      OPENAI_API_KEY: "${OPENAI_API_KEY:-}" # forward host key if present
      PYTHONPATH: "/app:/app/cursor_client_example"
    depends_on:
      - api
    tty: true
    stdin_open: true
    working_dir: /app

volumes:
  db_data: